// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {updater} from '../models';
import {diagnostics} from '../models';
import {app} from '../models';

export function AddProfile(arg1:string):Promise<config.Profile>;

export function CheckUpdate():Promise<updater.Asset>;

export function DeleteGame():Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DownloadAndLaunch(arg1:string):Promise<void>;

export function GetCrashReports():Promise<Array<diagnostics.CrashReport>>;

export function GetCurrentProfile():Promise<config.Profile>;

export function GetLauncherVersion():Promise<string>;

export function GetLogs():Promise<string>;

export function GetNews():Promise<Array<app.BlogPost>>;

export function GetNick():Promise<string>;

export function GetProfiles():Promise<Array<config.Profile>>;

export function GetSettings():Promise<config.GameSettings>;

export function GetVersions(arg1:string):Promise<app.GameVersions>;

export function OpenFolder():Promise<void>;

export function RunDiagnostics():Promise<app.DiagnosticReport>;

export function SaveDiagnosticReport():Promise<string>;

export function SaveSettings(arg1:config.GameSettings):Promise<void>;

export function SetCurrentProfile(arg1:string):Promise<void>;

export function SetNick(arg1:string):Promise<void>;

export function StopGame():Promise<void>;

export function Update():Promise<void>;

export function UpdateProfile(arg1:string,arg2:string):Promise<void>;
