// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProfile(arg1) {
  return window['go']['app']['App']['AddProfile'](arg1);
}

export function CheckUpdate() {
  return window['go']['app']['App']['CheckUpdate']();
}

export function DeleteGame() {
  return window['go']['app']['App']['DeleteGame']();
}

export function DeleteProfile(arg1) {
  return window['go']['app']['App']['DeleteProfile'](arg1);
}

export function DownloadAndLaunch(arg1) {
  return window['go']['app']['App']['DownloadAndLaunch'](arg1);
}

export function GetCrashReports() {
  return window['go']['app']['App']['GetCrashReports']();
}

export function GetCurrentProfile() {
  return window['go']['app']['App']['GetCurrentProfile']();
}

export function GetLauncherVersion() {
  return window['go']['app']['App']['GetLauncherVersion']();
}

export function GetLogs() {
  return window['go']['app']['App']['GetLogs']();
}

export function GetNews() {
  return window['go']['app']['App']['GetNews']();
}

export function GetNick() {
  return window['go']['app']['App']['GetNick']();
}

export function GetProfiles() {
  return window['go']['app']['App']['GetProfiles']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetVersions(arg1) {
  return window['go']['app']['App']['GetVersions'](arg1);
}

export function OpenFolder() {
  return window['go']['app']['App']['OpenFolder']();
}

export function RunDiagnostics() {
  return window['go']['app']['App']['RunDiagnostics']();
}

export function SaveDiagnosticReport() {
  return window['go']['app']['App']['SaveDiagnosticReport']();
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SetCurrentProfile(arg1) {
  return window['go']['app']['App']['SetCurrentProfile'](arg1);
}

export function SetNick(arg1) {
  return window['go']['app']['App']['SetNick'](arg1);
}

export function StopGame() {
  return window['go']['app']['App']['StopGame']();
}

export function Update() {
  return window['go']['app']['App']['Update']();
}

export function UpdateProfile(arg1, arg2) {
  return window['go']['app']['App']['UpdateProfile'](arg1, arg2);
}
