// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadAndLaunch(arg1) {
  return window['go']['main']['App']['DownloadAndLaunch'](arg1);
}

export function GetVersions() {
  return window['go']['main']['App']['GetVersions']();
}

export function Update() {
  return window['go']['main']['App']['Update']();
}
