// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadGame() {
  return window['go']['main']['App']['DownloadGame']();
}

export function LaunchGame() {
  return window['go']['main']['App']['LaunchGame']();
}
