// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadAndLaunch(arg1:string):Promise<void>;

export function GetVersions():Promise<string|string>;

export function Update():Promise<void>;
